### ISSUE TITLE
Using with Starling framework

### ISSUE THREAD

**Issue by andrius-k** [MaxDidIt/firetype#3]
Hello, 
first of all very nice project, congrats and thanks for it :)

But I have one problem though. I just can't get it working along with Starling framework. I pass Starling.context when instantiating HardwareText, like that:
_hardwareText = new HardwareText(Starling.context); 
And I also create new Matrix3d like shown in a tutorial. But I have no luck. No text is visible at all.
Any hel will be appreciated :)

**Comment by MaxDidIt** [comment]
Hi Andrius,

sorry for letting you wait. You have to give me more details before I
can help you.
Are you appending any scaling to the Matrix3D object?
Are you calling the render() method of the text's cache?
Also, you have to make sure that Starling is sharing the 3D context, as
described here:
http://wiki.starling-framework.org/tutorials/combining_starling_with_other_stage3d_frameworks

Maybe this helps you already, otherwise get back to me.

Best regards,

Max

Am 14.07.2013 18:41, schrieb Andrius123:

**Comment by andrius-k** [comment]
Hello Max, thanks allot for your response :)

Yes, the tutorial you showed me helped me, I can share the same context for both Starling and FireType. But I can only use FireType in base project as3 class. Not in any other class extending Starling Sprite. Showing text only in base class is not an option because Starling content is on top of FireType. This is the code that I use to show text in Starling classes:

_hardwareText = new HardwareText(FireType._context3d); 
_hardwareText.text = "Hello World!\nThis text is being rendered using firetype!Hello World!\nThis text is being rendered using firetype!";  
_hardwareText.scaleX = _hardwareText.scaleY = 0.02; 
_hardwareText.x = -320; 

var viewProjectionRawData:Vector.<Number> = new Vector.<Number>(); 
viewProjectionRawData.push( 2 / stage.stageWidth, 0, 0, 0, // 
0, 2 / stage.stageHeight, 0, 0, // 
0, 0, -2, -1, // 
0, 0, 0, 1); 

var viewProjection:Matrix3D = new Matrix3D(viewProjectionRawData); 

_hardwareText.calculateTransformations(viewProjection, true); 

Thanks in advance ;)

The other question: will it be possible to use FireType text as Starling DisplayObject and for example put to Feathers components like Scroller? Which would be very cool :)

**Comment by MaxDidIt** [comment]
Hi Andrius,

good news: I've sat down and implemented a basic Starling integration
for firetype. You can now use FiretypeStarlingTextField as a Starling
DisplayObject and add it into Starling's display list.

I've updated the README on https://github.com/MaxDidIt/firetype to
include the download link to the newest version of the library and a
short tutorial on how to use the new class.

Let me know if this has helped you!

**Comment by andrius-k** [comment]
Hey Max once again! In deed it did help :) I can display Firetype text in Starling classes without any problems now. Your effort on making Firetype possible to use in Starling is very much appreciated! A huge thanks :)

I will do some tests on performance of Firetype and will let you know of my results :)
Thanks again, Andrius

**Comment by MaxDidIt** [comment]
Awesome, thank you :-) I'm looking forward to see the results!

**Comment by radubirsan** [comment]
Performance sucks
